services:
  - type: web
    name: social-media-video-manager
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.19.0 